-- Seed: 90 Indian users for Orchestro
-- Password for all users: Welcome@123
-- BCrypt hash (cost 10): $2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W
-- Run: psql -U postgres -d <your_db> -f seed_users.sql

INSERT INTO users (username, email, password_hash, role, created_at) VALUES

-- ADMIN (5)
('aarav.sharma',    'aarav.sharma@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'ADMIN',     NOW()),
('priya.mehta',     'priya.mehta@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'ADMIN',     NOW()),
('rajesh.iyer',     'rajesh.iyer@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'ADMIN',     NOW()),
('ananya.nair',     'ananya.nair@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'ADMIN',     NOW()),
('vikram.reddy',    'vikram.reddy@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'ADMIN',     NOW()),

-- MANAGER (20)
('rohan.gupta',     'rohan.gupta@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('sneha.joshi',     'sneha.joshi@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('karan.patel',     'karan.patel@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('divya.singh',     'divya.singh@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('manish.verma',    'manish.verma@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('kavya.rao',       'kavya.rao@orchstro.com',       '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('siddharth.das',   'siddharth.das@orchstro.com',   '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('pooja.chopra',    'pooja.chopra@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('arjun.mishra',    'arjun.mishra@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('neha.kapoor',     'neha.kapoor@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('gaurav.saxena',   'gaurav.saxena@orchstro.com',   '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('ishita.bose',     'ishita.bose@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('rahul.desai',     'rahul.desai@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('tanvi.khanna',    'tanvi.khanna@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('dev.pillai',      'dev.pillai@orchstro.com',      '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('ritu.agarwal',    'ritu.agarwal@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('yash.banerjee',   'yash.banerjee@orchstro.com',   '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('simran.malhotra', 'simran.malhotra@orchstro.com', '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),
('harsh.tiwari',    'harsh.tiwari@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'MANAGER',   NOW()),

-- DEVELOPER (65)
('amit.kumar',      'amit.kumar@orchstro.com',      '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('deepa.ghosh',     'deepa.ghosh@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('nikhil.jain',     'nikhil.jain@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('sakshi.arora',    'sakshi.arora@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('pranav.goyal',    'pranav.goyal@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('madhuri.sinha',   'madhuri.sinha@orchstro.com',   '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('vikas.yadav',     'vikas.yadav@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('komal.trivedi',   'komal.trivedi@orchstro.com',   '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('dhruv.chaudhary', 'dhruv.chaudhary@orchstro.com', '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('ankita.dubey',    'ankita.dubey@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('mohit.pandey',    'mohit.pandey@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('swati.varma',     'swati.varma@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('kunal.mukherjee', 'kunal.mukherjee@orchstro.com', '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('nisha.chatterjee','nisha.chatterjee@orchstro.com','$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('saurabh.deshpande','saurabh.deshpande@orchstro.com','$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W','DEVELOPER',NOW()),
('kritika.shukla',  'kritika.shukla@orchstro.com',  '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('naveen.pande',    'naveen.pande@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('vandana.srivastava','vandana.srivastava@orchstro.com','$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W','DEVELOPER',NOW()),
('ashok.chakraborty','ashok.chakraborty@orchstro.com','$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W','DEVELOPER',NOW()),
('gayatri.nair',    'gayatri.nair@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('pankaj.reddy',    'pankaj.reddy@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('trisha.mehta',    'trisha.mehta@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('ishan.gupta',     'ishan.gupta@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('lakshmi.sharma',  'lakshmi.sharma@orchstro.com',  '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('hemant.joshi',    'hemant.joshi@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('naina.patel',     'naina.patel@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('vijay.singh',     'vijay.singh@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('aisha.verma',     'aisha.verma@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('sandeep.das',     'sandeep.das@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('meera.iyer',      'meera.iyer@orchstro.com',      '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('rakesh.bose',     'rakesh.bose@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('uma.pillai',      'uma.pillai@orchstro.com',      '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('nitin.saxena',    'nitin.saxena@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('shreya.kapoor',   'shreya.kapoor@orchstro.com',   '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('rajan.malhotra',  'rajan.malhotra@orchstro.com',  '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('tanya.tiwari',    'tanya.tiwari@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('suresh.rao',      'suresh.rao@orchstro.com',      '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('prateek.agarwal', 'prateek.agarwal@orchstro.com', '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('anjali.banerjee', 'anjali.banerjee@orchstro.com', '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('gopal.mishra',    'gopal.mishra@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('ravi.desai',      'ravi.desai@orchstro.com',      '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('bharat.chopra',   'bharat.chopra@orchstro.com',   '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('poornima.yadav',  'poornima.yadav@orchstro.com',  '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('sachin.khanna',   'sachin.khanna@orchstro.com',   '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('deepika.ghosh',   'deepika.ghosh@orchstro.com',   '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('vivek.srivastava','vivek.srivastava@orchstro.com','$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('shilpa.dubey',    'shilpa.dubey@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('ajay.pande',      'ajay.pande@orchstro.com',      '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('rekha.varma',     'rekha.varma@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('sumit.chakraborty','sumit.chakraborty@orchstro.com','$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W','DEVELOPER',NOW()),
('archana.jain',    'archana.jain@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('tarun.arora',     'tarun.arora@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('chitra.goyal',    'chitra.goyal@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('manoj.singh',     'manoj.singh@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('sudha.nair',      'sudha.nair@orchstro.com',      '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('kapil.reddy',     'kapil.reddy@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('sunita.mehta',    'sunita.mehta@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('lalit.sharma',    'lalit.sharma@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('padma.iyer',      'padma.iyer@orchstro.com',      '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('girish.bose',     'girish.bose@orchstro.com',     '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('nalini.pillai',   'nalini.pillai@orchstro.com',   '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('vinod.saxena',    'vinod.saxena@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('kamla.kapoor',    'kamla.kapoor@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('harish.malhotra', 'harish.malhotra@orchstro.com', '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('veena.tiwari',    'veena.tiwari@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('dinesh.rao',      'dinesh.rao@orchstro.com',      '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('mala.agarwal',    'mala.agarwal@orchstro.com',    '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW()),
('ramesh.banerjee', 'ramesh.banerjee@orchstro.com', '$2a$10$de5RzwZluY.flUvfoD1JYOJwM/rVBJnggCsoqpyFZnAgoinDCEk7W', 'DEVELOPER', NOW());
